# Generated by Django 6.0.2 on 2026-03-14 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Colores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Formas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marcacontactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcacontacto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(blank=True, choices=[('Monturas oftálmicas', 'Monturas oftálmicas'), ('Monturas Solares', 'Monturas Solares'), ('Lentes de Contacto', 'Lentes de Contacto'), ('Monturas de Marca', 'Monturas de Marca'), ('Líquidos', 'Líquidos'), ('Accesorios', 'Accesorios')], max_length=50, null=True)),
                ('nuevo', models.BooleanField(default=False)),
                ('marca', models.CharField(max_length=20)),
                ('categoria', models.CharField(blank=True, choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre'), ('Niño', 'Niño')], max_length=20, null=True)),
                ('material', models.CharField(blank=True, choices=[('Fibra de carbono', 'Fibra de carbono'), ('Acetato', 'Acetato'), ('Carey', 'Carey'), ('TR90', 'TR90'), ('Aluminium', 'Aluminium'), ('Engomado', 'Engomado'), ('Otros', 'Otros')], max_length=20, null=True)),
                ('forma', models.CharField(blank=True, choices=[('Agatado', 'Agatado'), ('Almendra', 'Almendra'), ('Piloto', 'Piloto'), ('Cuadrado', 'Cuadrado'), ('Redondo', 'Redondo'), ('Exagonal', 'Exagonal'), ('Otros', 'Otros')], max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('talla_luna', models.CharField(blank=True, max_length=5, null=True)),
                ('puente', models.CharField(blank=True, max_length=5, null=True)),
                ('largo', models.CharField(blank=True, max_length=5, null=True)),
                ('ancho', models.CharField(blank=True, max_length=5, null=True)),
                ('altura', models.CharField(blank=True, max_length=5, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('talla', models.CharField(blank=True, choices=[('Grande', 'Grande'), ('Mediana', 'Mediana'), ('Chica', 'Chica')], max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('costo_promedio', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('imagenF', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagenD', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagenL', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('condicion', models.CharField(blank=True, choices=[('Miopia e Hipermetropia', 'Miopia e Hipermetropia'), ('Astigmatismo', 'Astigmatismo'), ('Presbicia', 'Presbicia')], max_length=50, null=True)),
                ('uso', models.CharField(blank=True, choices=[('Diario', 'Diario'), ('Mensual', 'Mensual'), ('Cosmetico', 'Cosmetico')], max_length=20, null=True)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uso', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuevo', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('cod', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('disponible', models.BooleanField(blank=True, default=True, null=True)),
                ('clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.clases')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.colores')),
                ('forma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.formas')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.generos')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.marcas')),
                ('marcacontacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.marcacontactos')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.materiales')),
                ('talla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.tallas')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.tipos')),
                ('uso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.usos')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='store.producto')),
            ],
        ),
    ]
