# Generated by Django 6.0.2 on 2026-03-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre'), ('Nino', 'Nino')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(choices=[('Ray-Ban', 'Ray-Ban'), ('OaKley', 'OaKley'), ('Nike', 'Nike'), ('Guess', 'Guess'), ('Tommy-Hilfiger', 'Tommy-Hilfiger'), ('Arnette', 'Arnette'), ('Nano', 'Nano'), ('Otros', 'Otros')], max_length=20),
        ),
    ]
