# Generated by Django 6.0.2 on 2026-03-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_producto_categoria_alter_producto_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(choices=[('Ray-Ban', 'Ray-Ban'), ('OaKley', 'OaKley'), ('Nike', 'Nike'), ('Guess', 'Guess'), ('Tommy-Hilfiger', 'Tommy-Hilfiger'), ('Arnette', 'Arnette'), ('Nano', 'Nano'), ('Otros', 'Otros'), ('Acuvue', 'Acuvue'), ('Air Optix', 'Air Optix'), ('Dailies Aqua', 'Dailies Aqua'), ('Freshlook', 'Freshlook'), ('Licryl', 'Licryl'), ('Soflens', 'Soflens'), ('Purevision', 'Purevision'), ('Otros', 'Otros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Monturas oftálmicas', 'Monturas oftálmicas'), ('Monturas Solares', 'Monturas Solares'), ('Lentes de Contacto', 'Lentes de Contacto'), ('Monturas de Marca', 'Monturas de Marca'), ('Líquidos', 'Líquidos'), ('Accesorios', 'Accesorios'), ('Blandos', 'Blandos'), ('Rigidos', 'Rigidos'), ('Descartables', 'Descartables')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='uso',
            field=models.CharField(blank=True, choices=[('Diario', 'Diario'), ('Mensual', 'Mensual'), ('Anual', 'Anual'), ('Cosmetico', 'Cosmetico')], max_length=20, null=True),
        ),
    ]
