# Generated by Django 6.0.2 on 2026-03-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_producto_marca_alter_producto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='condicion',
            field=models.CharField(blank=True, choices=[('Miopia-e-Hipermetropia', 'Miopia-e-Hipermetropia'), ('Astigmatismo', 'Astigmatismo'), ('Presbicia', 'Presbicia')], max_length=50, null=True),
        ),
    ]
