# Generated by Django 6.0.2 on 2026-04-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_producto_condicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo_promedio',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='forma',
            field=models.CharField(blank=True, choices=[('Agatado', 'Agatado'), ('Almendra', 'Almendra'), ('Aviador', 'Aviador'), ('Cuadrado', 'Cuadrado'), ('Redondo', 'Redondo'), ('Exagonal', 'Exagonal'), ('Otros', 'Otros')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, choices=[('Ray-Ban', 'Ray-Ban'), ('OaKley', 'OaKley'), ('Nike', 'Nike'), ('Guess', 'Guess'), ('Tommy-Hilfiger', 'Tommy-Hilfiger'), ('Arnette', 'Arnette'), ('Nano', 'Nano'), ('Otros', 'Otros'), ('Acuvue', 'Acuvue'), ('Air-Optix', 'Air-Optix'), ('Dailies-Aqua', 'Dailies-Aqua'), ('Freshlook', 'Freshlook'), ('Licryl', 'Licryl'), ('Soflens', 'Soflens'), ('Purevision', 'Purevision'), ('Otros', 'Otros')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nuevo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Monturas oftálimcas', 'Monturas oftálimcas'), ('Monturas Solares', 'Monturas Solares'), ('Lentes de Contacto', 'Lentes de Contacto'), ('Monturas de Marca', 'Monturas de Marca'), ('Líquidos', 'Líquidos'), ('Accesorios', 'Accesorios')], max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='producto',
            table='core_producto',
        ),
    ]
