# Generated by Django 6.0.2 on 2026-05-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_producto_activo_alter_producto_costo_promedio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='material',
            field=models.CharField(blank=True, choices=[('Fibra-de-carbono', 'Fibra-de-carbono'), ('Acetato', 'Acetato'), ('Carey', 'Carey'), ('TR90', 'TR90'), ('Aluminium', 'Aluminium'), ('Engomado', 'Engomado'), ('Otros', 'Otros')], max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='producto',
            table=None,
        ),
    ]
